//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping
    {
        public int Id { get; set; }
        public decimal Summa { get; set; }
        public int BuyerId { get; set; }
    
        public virtual Buyer Buyer { get; set; }
    }
}
